# configs/joint_face_fixation_density.yaml
input_modality: fixation_density_vectors
output_modality: joint_face_fixation_density
face_label: face
normalize: true

use_parallel: true
test_single: false
